### ISSUE TITLE
MemoryError when running the examples

### ISSUE THREAD

**Issue by ethene** [carpedm20/deep-rl-tensorflow#20]
I'm getting the MemoryError. Ubuntu /2Gb ram + 4 Gb gwap:

Traceback (most recent call last):
  File "main.py", line 168, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 160, in main
    agent = TrainAgent(sess, pred_network, env, stat, conf, target_network=target_network)
  File "/home/strky/deep-rl-tensorflow/agents/deep_q.py", line 13, in __init__
    super(DeepQ, self).__init__(sess, pred_network, env, stat, conf, target_network=target_network)
  File "/home/strky/deep-rl-tensorflow/agents/agent.py", line 53, in __init__
    conf.batch_size, conf.history_length, conf.memory_size, conf.observation_dims)
  File "/home/strky/deep-rl-tensorflow/agents/experience.py", line 15, in __init__
    self.observations = np.empty([self.memory_size] + observation_dims, dtype=np.uint8)
MemoryError

**Comment by ppwwyyxx** [comment]
You memory (even with swap) is not enough to hold the experience replay buffer.
