### ISSUE TITLE
gym env.monitor.start should be replaced for new gym version:

### ISSUE THREAD

**Issue by ethene** [carpedm20/deep-rl-tensorflow#22]
Traceback (most recent call last):
  File "main.py", line 172, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "main.py", line 169, in main
    agent.play(conf.ep_end)
  File "../deep-rl-tensorflow/agents/agent.py", line 101, in play
    self.env.env.monitor.start(gym_dir)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 92, in monitor
    raise error.Error("env.monitor has been deprecated as of 12/23/2016. Remove your call to `env.monitor.start(directory)` and instead wrap your env with `env = gym.wrappers.Monitor(env, directory)` to record data.")
gym.error.Error: env.monitor has been deprecated as of 12/23/2016. Remove your call to `env.monitor.start(directory)` and instead wrap your env with `env = gym.wrappers.Monitor(env, directory)` to record data.

**Comment by AlexZhou1995** [comment]
I got the same problem
