### ISSUE TITLE
can't run in my pc

### ISSUE THREAD

**Issue by dave-yxw** [carpedm20/deep-rl-tensorflow#25]
<pre>
Traceback (most recent call last):
  File "main.py", line 168, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 163, in main
    agent.train(conf.t_train_max)
  File "/home/ddy/workspace/deep-rl-tensorflow/agents/agent.py", line 67, in train
    observation, reward, terminal = self.new_game()
  File "/home/ddy/workspace/deep-rl-tensorflow/environments/environment.py", line 87, in new_random_game
    self.lives = self.env.ale.lives()
AttributeError: 'TimeLimit' object has no attribute 'ale'
</pre>

**Comment by dave-yxw** [comment]
the command is :
python main.py --double_q=True --network_output_type=dueling --env_name=Breakout-v0

I have installed scipy opencv tensorflow_1.0 gym[all]

**Comment by dave-yxw** [comment]
It seems TimeLimit object is a wrapper of AtariEvn,

change line 22 in file environment.py:
<pre>
self.env = gym.make(env_name).env  # self.env = gym.make(env_name)
</pre>

and it works
