### ISSUE TITLE
Unknown command line flag 'data_format'

### ISSUE THREAD

**Issue by sonata2016** [carpedm20/deep-rl-tensorflow#36]
I got the following bug. Could you please help? Thank you!

$python main.py --network_header_type=nips --env_name=Breakout-v0 --use_gpu=False
Traceback (most recent call last):
  File "main.py", line 173, in <module>
    tf.app.run()
  File "/Documents/openai_gym/openai_gym/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 107, in main
    conf.data_format = 'NHWC'
  File "/Documents/openai_gym/openai_gym/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/Documents/openai_gym/openai_gym/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/Documents/openai_gym/openai_gym/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'data_format'

**Comment by florath** [comment]
This is because of a change in tf.
Created a patch / pull request to fix this: https://github.com/carpedm20/deep-rl-tensorflow/pull/39
